import type { Metadata } from "next";
import Link from "next/link";
import { PlaybackTimingLab } from "@/components/playback-timing-lab";
import styles from "@/components/playback-timing-lab.module.css";

export const metadata: Metadata = {
  title: "Animation Timing | 3D Lab",
  description: "Inspect uneven render intervals, frame-rate-independent playback, drift, and deterministic clip cross-fades.",
};

export default function AnimationTimingPage() {
  return (
    <main>
      <Link href="/" className={styles.backLink}>← Back to 3D fundamentals</Link>
      <header className={styles.pageHeader}>
        <p className="eyebrow">3d-lab / animation timing</p>
        <h1>Animation time should survive every dropped and delayed frame.</h1>
        <p className="lede">
          Replay a deliberately uneven sequence generated by the Rust playback layer. Compare elapsed-time sampling with a broken fixed-per-frame clock, then inspect the same timeline while two clips cross-fade with quaternion-safe rotation blending.
        </p>
      </header>
      <PlaybackTimingLab />
    </main>
  );
}
