import type { Metadata } from "next";
import Link from "next/link";
import { LodQualityLab } from "@/components/lod-quality-lab";
import styles from "@/components/lod-quality-lab.module.css";

export const metadata: Metadata = {
  title: "LOD & Mesh Simplification | 3D Lab",
  description: "Inspect Rust-generated mesh LODs, geometric error, screen-space selection, and hysteresis interactively.",
};

export default function LodPage() {
  return (
    <main>
      <Link href="/" className={styles.backLink}>← Back to 3D fundamentals</Link>
      <header className={styles.pageHeader}>
        <p className="eyebrow">3d-lab / LOD & mesh simplification</p>
        <h1>Spend triangles where they can still change the image.</h1>
        <p className="lede">
          Compare the source mesh with index buffers generated by the renderer-independent Rust simplifier, then move the virtual camera and see how a pixel-error budget plus hysteresis chooses a stable level of detail.
        </p>
      </header>
      <LodQualityLab />
    </main>
  );
}
